## Importing the Libraries for usage

In [3]:
import pandas as pd
import numpy as np
import matplotlib as mp

## Importing the CSV File using 'read_csv' and perform some inital analysis

In [4]:
layoff_data = pd.read_csv('layoffs.csv')
layoff_data

,company,location,total_laid_off,date,percentage_laid_off,industry,source,stage,funds_raised,country,date_added
0,Netflix,SF Bay Area,1000.0,10/14/2026,0.06,Media,https://www.cnbc.com/2026/10/14/netflix-layoff...,Post-IPO,121900.0,United States,10/15/2026
1,Lightspeed Commerce,"Montreal, Non-U.S.",250.0,10/13/2026,NaN,Retail,https://www.theglobeandmail.com/business/artic...,Post-IPO,1200.0,Canada,10/14/2026
2,XM Cyber,"Tel Aviv, Non-U.S.",250.0,10/13/2026,0.62,Security,https://www.calcalistech.com/ctechnews/article...,Acquired,49.0,Israel,10/15/2026
3,ShipHero,New York City,30.0,10/13/2026,NaN,Logistics,https://www.linkedin.com/posts/aaronandml_we-l...,Unknown,60.0,United States,10/15/2026
4,Character.AI,SF Bay Area,NaN,10/13/2026,1.00,AI,https://www.cnbc.com/2026/10/13/character-ai-c...,Series A,150.0,United States,10/14/2026
...,...,...,...,...,...,...,...,...,...,...,...
4628,Service,Los Angeles,NaN,3/16/2020,1.00,Travel,https://techcrunch.com/2020/03/16/travel-savin...,Seed,5.1,United States,8/31/2020
4629,HopSkipDrive,Los Angeles,8.0,3/13/2020,0.10,Transportation,https://layoffs.fyi/2020/04/02/hopskipdrive-la...,Unknown,45.0,United States,4/3/2020
4630,Panda Squad,SF Bay Area,6.0,3/13/2020,0.75,Consumer,https://twitter.com/danielsinger/status/123854...,Seed,1.0,United States,4/17/2020
4631,Tamara Mellon,Los Angeles,20.0,3/12/2020,0.40,Retail,https://layoffs.fyi/list/tamara-mellon/,Series C,90.0,United States,3/31/2020
4632,EasyPost,Salt Lake City,75.0,3/11/2020,NaN,Logistics,https://www.bizjournals.com/louisville/news/20...,Series A,12.0,United States,3/31/2020

In [4]:
layoff_data.shape

(4633, 11)

In [45]:
layoff_data.isnull().sum()

company                0
location               0
total_laid_off         0
date                   0
percentage_laid_off    0
industry               0
stage                  0
funds_raised           0
country                0
date_added             0
dtype: int64

In [6]:
layoff_data.nunique()

company                2999
location                273
total_laid_off          386
date                   1328
percentage_laid_off      82
industry                 30
source                 4370
stage                    16
funds_raised            770
country                  67
date_added             1112
dtype: int64

In [7]:
layoff_data.count()

company                4633
location               4632
total_laid_off         3024
date                   4633
percentage_laid_off    2900
industry               4631
source                 4630
stage                  4625
funds_raised           4083
country                4631
date_added             4633
dtype: int64

In [8]:
layoff_data['company'].value_counts()

company
Amazon          25
Google          19
Microsoft       18
Salesforce      15
Intel           13
                ..
Triplebyte       1
Ladder Life      1
Cabin            1
Character.AI     1
ShipHero         1
Name: count, Length: 2999, dtype: int64

### Finding the 'percentage_laid_off' null values by using 'isnull()' function and replace it with 0

In [9]:
print(layoff_data['percentage_laid_off'].isnull())

0       False
1        True
2       False
3        True
4       False
        ...
4628    False
4629    False
4630    False
4631    False
4632     True
Name: percentage_laid_off, Length: 4633, dtype: bool

In [14]:
print(layoff_data['percentage_laid_off'])

0       0.06
1        NaN
2       0.62
3        NaN
4       1.00
        ...
4628    1.00
4629    0.10
4630    0.75
4631    0.40
4632     NaN
Name: percentage_laid_off, Length: 4633, dtype: float64

In [5]:
layoff_data['percentage_laid_off'] = layoff_data['percentage_laid_off'].fillna(0)

In [6]:
print(layoff_data['percentage_laid_off'])
layoff_data

0       0.06
1       0.00
2       0.62
3       0.00
4       1.00
        ...
4628    1.00
4629    0.10
4630    0.75
4631    0.40
4632    0.00
Name: percentage_laid_off, Length: 4633, dtype: float64

,company,location,total_laid_off,date,percentage_laid_off,industry,source,stage,funds_raised,country,date_added
0,Netflix,SF Bay Area,1000.0,10/14/2026,0.06,Media,https://www.cnbc.com/2026/10/14/netflix-layoff...,Post-IPO,121900.0,United States,10/15/2026
1,Lightspeed Commerce,"Montreal, Non-U.S.",250.0,10/13/2026,0.00,Retail,https://www.theglobeandmail.com/business/artic...,Post-IPO,1200.0,Canada,10/14/2026
2,XM Cyber,"Tel Aviv, Non-U.S.",250.0,10/13/2026,0.62,Security,https://www.calcalistech.com/ctechnews/article...,Acquired,49.0,Israel,10/15/2026
3,ShipHero,New York City,30.0,10/13/2026,0.00,Logistics,https://www.linkedin.com/posts/aaronandml_we-l...,Unknown,60.0,United States,10/15/2026
4,Character.AI,SF Bay Area,NaN,10/13/2026,1.00,AI,https://www.cnbc.com/2026/10/13/character-ai-c...,Series A,150.0,United States,10/14/2026
...,...,...,...,...,...,...,...,...,...,...,...
4628,Service,Los Angeles,NaN,3/16/2020,1.00,Travel,https://techcrunch.com/2020/03/16/travel-savin...,Seed,5.1,United States,8/31/2020
4629,HopSkipDrive,Los Angeles,8.0,3/13/2020,0.10,Transportation,https://layoffs.fyi/2020/04/02/hopskipdrive-la...,Unknown,45.0,United States,4/3/2020
4630,Panda Squad,SF Bay Area,6.0,3/13/2020,0.75,Consumer,https://twitter.com/danielsinger/status/123854...,Seed,1.0,United States,4/17/2020
4631,Tamara Mellon,Los Angeles,20.0,3/12/2020,0.40,Retail,https://layoffs.fyi/list/tamara-mellon/,Series C,90.0,United States,3/31/2020
4632,EasyPost,Salt Lake City,75.0,3/11/2020,0.00,Logistics,https://www.bizjournals.com/louisville/news/20...,Series A,12.0,United States,3/31/2020

### Finding the 'industry' null values by using 'isnull()' function and replace it with the specific industry type by Company name

In [27]:
print(layoff_data[layoff_data['industry'].isnull()])

Empty DataFrame
Columns: [company, location, total_laid_off, date, percentage_laid_off, industry, source, stage, funds_raised, country, date_added]
Index: []

In [8]:
print(layoff_data.iloc[495])

company                                                             Eyeo
location                                               Cologne, Non-U.S.
total_laid_off                                                       NaN
date                                                           7/28/2025
percentage_laid_off                                                  0.4
industry                                                           Media
source                 https://www.adexchanger.com/privacy/eyeo-names...
stage                                                            Unknown
funds_raised                                                         NaN
country                                                          Germany
date_added                                                     7/30/2025
Name: 495, dtype: object

In [7]:
layoff_data.loc[495, 'industry'] = 'Media'

In [10]:
print(layoff_data.iloc[1562])

company                                                         Appsmith
location                                                     SF Bay Area
total_laid_off                                                      35.0
date                                                           9/22/2023
percentage_laid_off                                                 0.25
industry                                                            Data
source                 https://inc42.com/buzz/exclusive-insight-partn...
stage                                                           Series B
funds_raised                                                        51.0
country                                                    United States
date_added                                                     9/24/2023
Name: 1562, dtype: object

In [9]:
layoff_data.loc[1562, 'industry'] = 'Data'

###  Finding the 'location' null values by using 'isnull()' function and 
###  Replace it with the specific location by Country
###  Using the loc[] by index number

In [28]:
print(layoff_data[layoff_data['location'].isna()])

           company location  total_laid_off       date  percentage_laid_off  \
1520  Product Hunt      NaN             NaN  10/9/2023                  0.6

      industry                                             source     stage  \
1520  Consumer  https://techcrunch.com/2023/10/19/product-hunt...  Acquired

      funds_raised        country  date_added
1520           NaN  United States  10/15/2023

In [14]:
print(layoff_data.iloc[1520])

company                                                     Product Hunt
location                                                   San francisco
total_laid_off                                                       NaN
date                                                           10/9/2023
percentage_laid_off                                                  0.6
industry                                                        Consumer
source                 https://techcrunch.com/2023/10/19/product-hunt...
stage                                                           Acquired
funds_raised                                                         NaN
country                                                    United States
date_added                                                    10/15/2023
Name: 1520, dtype: object

In [13]:
layoff_data.loc[1520, 'location'] = 'San francisco'

### Finding the 'stage' null values by using 'isnull()' function and replace it with the Unkown

In [18]:
print(layoff_data[layoff_data['stage'].isnull()])

Empty DataFrame
Columns: [company, location, total_laid_off, date, percentage_laid_off, industry, source, stage, funds_raised, country, date_added]
Index: []

In [17]:
layoff_data.loc[[240, 281, 293, 2489, 3101, 3107, 3456, 3839 ], 'stage'] = 'Unknown'

### Finding the 'country' null values by using 'isnull()' function and replace it with the specific Location match country

In [23]:
print(layoff_data[layoff_data['country'].isnull()])

Empty DataFrame
Columns: [company, location, total_laid_off, date, percentage_laid_off, industry, source, stage, funds_raised, country, date_added]
Index: []

In [22]:
layoff_data.loc[1554, 'country'] = 'Germany'
layoff_data.loc[1840, 'country'] = 'Canada'

### Drop the source table for better analysis using the drop function

In [25]:
layoff_data = layoff_data.drop(['source'], axis=1)

In [26]:
layoff_data

,company,location,total_laid_off,date,percentage_laid_off,industry,stage,funds_raised,country,date_added
0,Netflix,SF Bay Area,1000.0,10/14/2026,0.06,Media,Post-IPO,121900.0,United States,10/15/2026
1,Lightspeed Commerce,"Montreal, Non-U.S.",250.0,10/13/2026,0.00,Retail,Post-IPO,1200.0,Canada,10/14/2026
2,XM Cyber,"Tel Aviv, Non-U.S.",250.0,10/13/2026,0.62,Security,Acquired,49.0,Israel,10/15/2026
3,ShipHero,New York City,30.0,10/13/2026,0.00,Logistics,Unknown,60.0,United States,10/15/2026
4,Character.AI,SF Bay Area,NaN,10/13/2026,1.00,AI,Series A,150.0,United States,10/14/2026
...,...,...,...,...,...,...,...,...,...,...
4628,Service,Los Angeles,NaN,3/16/2020,1.00,Travel,Seed,5.1,United States,8/31/2020
4629,HopSkipDrive,Los Angeles,8.0,3/13/2020,0.10,Transportation,Unknown,45.0,United States,4/3/2020
4630,Panda Squad,SF Bay Area,6.0,3/13/2020,0.75,Consumer,Seed,1.0,United States,4/17/2020
4631,Tamara Mellon,Los Angeles,20.0,3/12/2020,0.40,Retail,Series C,90.0,United States,3/31/2020
4632,EasyPost,Salt Lake City,75.0,3/11/2020,0.00,Logistics,Series A,12.0,United States,3/31/2020

### Finding the 'total_laid_off' null values by using 'isnull()' function and replace it with 0 for better analysis

In [31]:
print(layoff_data[layoff_data['total_laid_off'].isnull()])

            company              location  total_laid_off        date  \
4      Character.AI           SF Bay Area             NaN  10/13/2026
5          Airtable           SF Bay Area             NaN  10/12/2026
6        YoLa Fresh  Casablanca, Non-U.S.             NaN  10/12/2026
9            Amazon               Seattle             NaN   10/7/2026
10           Hopper    Montreal, Non-U.S.             NaN   10/7/2026
...             ...                   ...             ...         ...
4617         Vacasa              Portland             NaN   3/20/2020
4622      Anyvision    Tel Aviv, Non-U.S.             NaN   3/19/2020
4623          Popin         New York City             NaN   3/19/2020
4624  Tuft & Needle               Phoenix             NaN   3/19/2020
4628        Service           Los Angeles             NaN   3/16/2020

      percentage_laid_off  industry     stage  funds_raised        country  \
4                     1.0        AI  Series A         150.0  United States
5                     0.0   Product  Acquired        1400.0  United States
6                     1.0      Food      Seed           9.0        Morocco
9                     0.0    Retail  Post-IPO        8100.0  United States
10                    0.0    Travel   Unknown         730.0         Canada
...                   ...       ...       ...           ...            ...
4617                  0.0    Travel  Series C         526.0  United States
4622                  0.0  Security  Series A          74.0         Israel
4623                  1.0   Fitness   Unknown          13.0  United States
4624                  0.0    Retail  Acquired           NaN  United States
4628                  1.0    Travel      Seed           5.1  United States

      date_added
4     10/14/2026
5     10/14/2026
6     10/14/2026
9      10/8/2026
10     10/8/2026
...          ...
4617   3/28/2020
4622   3/30/2020
4623    4/6/2020
4624    4/5/2020
4628   8/31/2020

[1609 rows x 10 columns]

In [35]:
print(layoff_data.iloc[4617])

company                       Vacasa
location                    Portland
total_laid_off                  10.0
date                       3/20/2020
percentage_laid_off              0.0
industry                      Travel
stage                       Series C
funds_raised                   526.0
country                United States
date_added                 3/28/2020
Name: 4617, dtype: object

In [40]:
layoff_data['total_laid_off'] = layoff_data['total_laid_off'].fillna(0)

### Finding the 'funds_raised' null values by using 'isnull()' function and replace it with 0 for better analysis

In [41]:
print(layoff_data[layoff_data['funds_raised'].isnull()])

             company            location  total_laid_off       date  \
25            Oracle         SF Bay Area            10.0  9/14/2026
27    Bitcoin Suisse    Zurich, Non-U.S.            60.0  9/11/2026
31           Samsung  Gurugram, Non-U.S.            80.0   9/8/2026
37            Orionx  Santiago, Non-U.S.            10.0   9/3/2026
44          Synopsys         SF Bay Area           128.0   9/1/2026
...              ...                 ...             ...        ...
4594            Takl           Nashville           130.0  3/24/2020
4598           Flowr   Toronto, Non-U.S.            10.0  3/24/2020
4605            Drip      Salt Lake City            20.0  3/23/2020
4619          Ejento         SF Bay Area            84.0  3/19/2020
4624   Tuft & Needle             Phoenix            10.0  3/19/2020

      percentage_laid_off    industry     stage  funds_raised        country  \
25                   0.00       Other  Post-IPO           NaN  United States
27                   0.50      Crypto  Series A           NaN    Switzerland
31                   0.00    Hardware  Post-IPO           NaN          India
37                   1.00      Crypto  Series A           NaN          Chile
44                   0.00       Other  Post-IPO           NaN  United States
...                   ...         ...       ...           ...            ...
4594                 0.00    Consumer   Unknown           NaN  United States
4598                 0.25      Retail   Unknown           NaN         Canada
4605                 0.00   Marketing  Acquired           NaN  United States
4619                 1.00  Recruiting   Unknown           NaN  United States
4624                 0.00      Retail  Acquired           NaN  United States

     date_added
25    9/16/2026
27    9/14/2026
31     9/9/2026
37     9/7/2026
44     9/2/2026
...         ...
4594   4/2/2020
4598  3/28/2020
4605   4/1/2020
4619  3/28/2020
4624   4/5/2020

[550 rows x 10 columns]

In [39]:
print(layoff_data.iloc[25])
print(layoff_data.iloc[26])

company                       Oracle
location                 SF Bay Area
total_laid_off                  10.0
date                       9/14/2026
percentage_laid_off              0.0
industry                       Other
stage                       Post-IPO
funds_raised                     NaN
country                United States
date_added                 9/16/2026
Name: 25, dtype: object
company                            Twiga
location               Nairobi, Non-U.S.
total_laid_off                      10.0
date                           9/14/2026
percentage_laid_off                  1.0
industry                            Food
stage                           Series C
funds_raised                       157.0
country                            Kenya
date_added                     10/8/2026
Name: 26, dtype: object

In [44]:
layoff_data['funds_raised'] = layoff_data['funds_raised'].fillna(0)

In [46]:
layoff_data

,company,location,total_laid_off,date,percentage_laid_off,industry,stage,funds_raised,country,date_added
0,Netflix,SF Bay Area,1000.0,10/14/2026,0.06,Media,Post-IPO,121900.0,United States,10/15/2026
1,Lightspeed Commerce,"Montreal, Non-U.S.",250.0,10/13/2026,0.00,Retail,Post-IPO,1200.0,Canada,10/14/2026
2,XM Cyber,"Tel Aviv, Non-U.S.",250.0,10/13/2026,0.62,Security,Acquired,49.0,Israel,10/15/2026
3,ShipHero,New York City,30.0,10/13/2026,0.00,Logistics,Unknown,60.0,United States,10/15/2026
4,Character.AI,SF Bay Area,10.0,10/13/2026,1.00,AI,Series A,150.0,United States,10/14/2026
...,...,...,...,...,...,...,...,...,...,...
4628,Service,Los Angeles,10.0,3/16/2020,1.00,Travel,Seed,5.1,United States,8/31/2020
4629,HopSkipDrive,Los Angeles,8.0,3/13/2020,0.10,Transportation,Unknown,45.0,United States,4/3/2020
4630,Panda Squad,SF Bay Area,6.0,3/13/2020,0.75,Consumer,Seed,1.0,United States,4/17/2020
4631,Tamara Mellon,Los Angeles,20.0,3/12/2020,0.40,Retail,Series C,90.0,United States,3/31/2020
4632,EasyPost,Salt Lake City,75.0,3/11/2020,0.00,Logistics,Series A,12.0,United States,3/31/2020

In [47]:
layoff_data.describe()

       total_laid_off  percentage_laid_off   funds_raised
count     4633.000000          4633.000000    4633.000000
mean       205.608677             0.185535     828.182624
std        907.864995             0.282251    4953.794080
min          3.000000             0.000000       0.000000
25%         10.000000             0.000000      26.000000
50%         40.000000             0.080000     133.000000
75%        120.000000             0.200000     431.000000
max      22000.000000             1.000000  121900.000000

### Create a Category that have high and low layoff by using Numpy library
#### Used the filter where for categories the layoff that 
#### If the Total layoff >= 1000 is High and lesser is Low

In [57]:
layoff_data['layoff_category'] = np.where(
    layoff_data['total_laid_off'] >= 1000,
    'High',
    'Low'
)
print(layoff_data['layoff_category'])

0       High
1        Low
2        Low
3        Low
4        Low
        ...
4628     Low
4629     Low
4630     Low
4631     Low
4632     Low
Name: layoff_category, Length: 4633, dtype: object

## Export the File to Create Interactive dashboard in PowerBI

In [59]:
layoff_data.to_csv('layoffs_cleaned.csv', index=False)